# Generated by Django 3.1.2 on 2020-11-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.BinaryField(editable=True)),
                ('content', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shipping', models.CharField(choices=[('yes', 'shipping is possible'), ('no', 'shipping is not possible')], default='no', max_length=100)),
                ('sell_or_exchange', models.CharField(choices=[('sell', 'for sell'), ('exchange', 'for exchange'), ('sell or exchange', 'for sell or exchange')], default='sell', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.category')),
            ],
        ),
    ]
