# Generated by Django 3.1.3 on 2020-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('1', 'szafy'), ('2', 'komody'), ('3', 'sofy'), ('4', 'zestawy wypoczynkowe'), ('5', 'meblościanki'), ('6', 'ławy i stoliki'), ('7', 'krzesła')], max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(upload_to='#'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sell_or_exchange',
            field=models.CharField(choices=[('1', 'for sell'), ('2', 'for exchange'), ('3', 'for sell or exchange')], default='sell', max_length=20),
        ),
    ]
