# Generated by Django 3.1.3 on 2020-11-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20201105_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('szafy', 'szafy'), ('komody', 'komody'), ('sofy', 'sofy'), ('zestawy wypoczynkowe', 'zestawy wypoczynkowe'), ('meblościanki', 'meblościanki'), ('ławy i stoliki', 'ławy i stoliki'), ('krzesła', 'krzesła')], max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sell_or_exchange',
            field=models.CharField(choices=[('na sprzedaż', 'for sell'), ('na wymianę', 'for exchange'), ('na sprzedaz lub wymianę', 'for sell or exchange')], max_length=100),
        ),
    ]
