# Generated by Django 3.1.2 on 2020-10-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201031_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='podaj cenę', max_digits=10, verbose_name='Cena'),
        ),
    ]
