# Generated by Django 3.1.2 on 2020-10-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201031_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.user', verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Imię'),
        ),
    ]
